#!/usr/bin/env bash
# Git alias catalog helpers and Phase 3 apply logic (Unix).

: "${BOTSTRAP_ROOT:?BOTSTRAP_ROOT must be set}"

# shellcheck source=lib/log.sh
source "${BOTSTRAP_ROOT}/lib/log.sh"
# shellcheck source=lib/bash-compat.sh
source "${BOTSTRAP_ROOT}/lib/bash-compat.sh"

botstrap_git_aliases_yaml() {
  printf '%s/configs/git/aliases.yaml' "${BOTSTRAP_ROOT}"
}

botstrap_git_aliases_config_dir() {
  printf '%s/.config/botstrap' "${HOME}"
}

botstrap_git_aliases_fragment_path() {
  printf '%s/.config/botstrap/git-aliases' "${HOME}"
}

botstrap_git_aliases_env_path() {
  printf '%s/.config/botstrap/git-aliases.env' "${HOME}"
}

botstrap_git_aliases_user_gitconfig() {
  printf '%s/.gitconfig' "${HOME}"
}

# CSV of alias ids with default: true when defaults.enabled is true; empty otherwise.
botstrap_git_aliases_default_csv() {
  local yaml enabled
  yaml="$(botstrap_git_aliases_yaml)"
  [[ -f "${yaml}" ]] || return 0
  enabled="$(yq -r '.defaults.enabled // true' "${yaml}" 2>/dev/null || echo true)"
  [[ "${enabled}" == "true" ]] || return 0
  yq -r '.aliases[] | select(.default == true) | .id' "${yaml}" 2>/dev/null | paste -sd, -
}

# Resolve id to "name<TAB>command" from catalog; prints nothing if unknown.
botstrap_git_aliases_lookup() {
  local id="$1"
  local yaml
  yaml="$(botstrap_git_aliases_yaml)"
  [[ -f "${yaml}" ]] || return 1
  yq -r ".aliases[] | select(.id == \"${id}\") | [.name, .command] | @tsv" "${yaml}" 2>/dev/null || true
}

# Build preview lines: "id → command — description"
botstrap_git_aliases_preview_lines() {
  local yaml
  yaml="$(botstrap_git_aliases_yaml)"
  [[ -f "${yaml}" ]] || return 0
  yq -r '.aliases[] | "\(.id) → \(.command) — \(.description)"' "${yaml}" 2>/dev/null || true
}

# gum choose labels: "id → command"
botstrap_git_aliases_choose_labels() {
  local yaml
  yaml="$(botstrap_git_aliases_yaml)"
  [[ -f "${yaml}" ]] || return 0
  yq -r '.aliases[] | "\(.id) → \(.command)"' "${yaml}" 2>/dev/null || true
}

# Extract alias id from a gum choose label ("id → command").
botstrap_git_aliases_id_from_label() {
  local label="$1"
  printf '%s' "${label%% → *}"
}

# Read managed= csv from git-aliases.env (may be empty).
botstrap_git_aliases_read_managed_csv() {
  local env_file line
  env_file="$(botstrap_git_aliases_env_path)"
  [[ -f "${env_file}" ]] || return 0
  line="$(grep -m1 '^managed=' "${env_file}" 2>/dev/null || true)"
  [[ -n "${line}" ]] || return 0
  printf '%s' "${line#managed=}"
}

botstrap_git_aliases_csv_contains() {
  local csv="$1"
  local needle="$2"
  local part
  IFS=',' read -ra _parts <<<"${csv}"
  for part in "${_parts[@]}"; do
    part="${part//[[:space:]]/}"
    [[ "${part}" == "${needle}" ]] && return 0
  done
  return 1
}

botstrap_git_aliases_ensure_include() {
  local gitconfig fragment marker
  gitconfig="$(botstrap_git_aliases_user_gitconfig)"
  fragment="$(botstrap_git_aliases_fragment_path)"
  marker='# botstrap git-aliases'

  if grep -qF "${marker}" "${gitconfig}" 2>/dev/null; then
    return 0
  fi

  {
    printf '\n%s\n' "${marker}"
    printf '[include]\n'
    printf '\tpath = %s\n' "${fragment}"
  } >>"${gitconfig}"
  botstrap_log_info "Added git alias include to ${gitconfig}"
}

botstrap_git_aliases_remove_include() {
  local gitconfig="$1"
  local tmp skip line

  [[ -f "${gitconfig}" ]] || return 0
  tmp="$(mktemp)"
  skip=false
  while IFS= read -r line || [[ -n "${line}" ]]; do
    if [[ "${line}" == '# botstrap git-aliases' ]]; then
      skip=true
      continue
    fi
    if [[ "${skip}" == true ]]; then
      if [[ "${line}" =~ ^\[include\] ]]; then
        continue
      fi
      if [[ "${line}" =~ ^[[:space:]]*path[[:space:]]*= ]]; then
        skip=false
        continue
      fi
      if [[ -z "${line}" ]]; then
        skip=false
        continue
      fi
      skip=false
    fi
    printf '%s\n' "${line}"
  done <"${gitconfig}" >"${tmp}"
  if ! cmp -s "${gitconfig}" "${tmp}"; then
    mv -f "${tmp}" "${gitconfig}"
    botstrap_log_info "Removed git alias include from ${gitconfig}"
  else
    rm -f "${tmp}"
  fi
}

botstrap_git_aliases_apply() {
  local selection="${BOTSTRAP_GIT_ALIASES:-}"
  local yaml fragment env_file config_dir managed_csv
  local -a applied_ids=()
  local id lookup name command existing

  yaml="$(botstrap_git_aliases_yaml)"
  fragment="$(botstrap_git_aliases_fragment_path)"
  env_file="$(botstrap_git_aliases_env_path)"
  config_dir="$(botstrap_git_aliases_config_dir)"
  managed_csv="$(botstrap_git_aliases_read_managed_csv)"

  mkdir -p "${config_dir}"

  if [[ "${selection}" == "none" ]]; then
    rm -f "${fragment}"
    botstrap_git_aliases_remove_include "$(botstrap_git_aliases_user_gitconfig)"
    {
      printf '%s\n' '# Generated by Botstrap phase 3; git alias selection for reconfigure.'
      printf 'selected=none\n'
      printf 'managed=\n'
    } >"${env_file}"
    botstrap_log_info 'Git aliases skipped (BOTSTRAP_GIT_ALIASES=none).'
    return 0
  fi

  if [[ -z "${selection}" ]]; then
    selection="$(botstrap_git_aliases_default_csv)"
  fi

  if [[ -z "${selection}" ]]; then
    rm -f "${fragment}"
    botstrap_git_aliases_remove_include "$(botstrap_git_aliases_user_gitconfig)"
    {
      printf '%s\n' '# Generated by Botstrap phase 3; git alias selection for reconfigure.'
      printf 'selected=\n'
      printf 'managed=\n'
    } >"${env_file}"
    return 0
  fi

  if [[ ! -f "${yaml}" ]]; then
    botstrap_log_warn "Git alias catalog missing: ${yaml}"
    return 0
  fi

  if ! command -v git &>/dev/null; then
    botstrap_log_warn 'git not on PATH; skipping git alias setup.'
    return 0
  fi

  {
    printf '%s\n' '[alias]'
  } >"${fragment}.tmp"

  IFS=',' read -ra _sel_ids <<<"${selection}"
  for id in "${_sel_ids[@]}"; do
    id="${id//[[:space:]]/}"
    [[ -n "${id}" ]] || continue

    lookup="$(botstrap_git_aliases_lookup "${id}")"
    if [[ -z "${lookup}" ]]; then
      botstrap_log_warn "Unknown git alias id: ${id}"
      continue
    fi
    name="${lookup%%$'\t'*}"
    command="${lookup#*$'\t'}"

    existing="$(git config --global --get "alias.${name}" 2>/dev/null || true)"
    if [[ -n "${existing}" ]] && ! botstrap_git_aliases_csv_contains "${managed_csv}" "${name}"; then
      botstrap_log_warn "Skipping git alias ${name}: already set globally (not managed by Botstrap)."
      continue
    fi

    printf '\t%s = %s\n' "${name}" "${command}" >>"${fragment}.tmp"
    applied_ids+=("${name}")
  done

  if [[ ${#applied_ids[@]} -eq 0 ]]; then
    rm -f "${fragment}.tmp"
    rm -f "${fragment}"
    botstrap_git_aliases_remove_include "$(botstrap_git_aliases_user_gitconfig)"
    {
      printf '%s\n' '# Generated by Botstrap phase 3; git alias selection for reconfigure.'
      printf 'selected=%s\n' "${selection}"
      printf 'managed=\n'
    } >"${env_file}"
    botstrap_log_info 'No git aliases applied (conflicts or empty selection).'
    return 0
  fi

  mv -f "${fragment}.tmp" "${fragment}"
  botstrap_git_aliases_ensure_include

  local applied_csv managed_out
  applied_csv="$(printf '%s,' "${applied_ids[@]}")"
  applied_csv="${applied_csv%,}"
  managed_out="${applied_csv}"

  {
    printf '%s\n' '# Generated by Botstrap phase 3; git alias selection for reconfigure.'
    printf 'selected=%s\n' "${selection}"
    printf 'managed=%s\n' "${managed_out}"
  } >"${env_file}"

  botstrap_log_info "Applied ${#applied_ids[@]} git alias(es) to ${fragment}"
}

botstrap_git_aliases_uninstall() {
  local fragment env_file gitconfig
  fragment="$(botstrap_git_aliases_fragment_path)"
  env_file="$(botstrap_git_aliases_env_path)"
  gitconfig="$(botstrap_git_aliases_user_gitconfig)"

  botstrap_git_aliases_remove_include "${gitconfig}"
  if [[ -f "${fragment}" ]]; then
    rm -f "${fragment}"
    botstrap_log_info "Removed ${fragment}"
  fi
  if [[ "${1:-}" == "--purge" && -f "${env_file}" ]]; then
    rm -f "${env_file}"
    botstrap_log_info "Removed ${env_file}"
  fi
}
