#requires -Version 5.1
$ErrorActionPreference = 'Stop'
. (Join-Path $env:BOTSTRAP_ROOT 'lib\log.ps1')
. (Join-Path $env:BOTSTRAP_ROOT 'lib\pkg.ps1')
. (Join-Path $env:BOTSTRAP_ROOT 'lib\profile-windows.ps1')

Refresh-BotstrapPath

if (-not $env:BOTSTRAP_THEME) { $env:BOTSTRAP_THEME = 'catppuccin' }
if (-not $env:BOTSTRAP_EDITOR) { $env:BOTSTRAP_EDITOR = 'none' }

$root = $env:BOTSTRAP_ROOT
$configBase = Join-Path $env:USERPROFILE '.config'
$configRoot = Join-Path $configBase 'botstrap'
New-Item -ItemType Directory -Force -Path $configRoot | Out-Null
$coreToolsEnvPath = Join-Path $configRoot 'core-tools.env'
@(
    '# Generated by Botstrap phase 3; persisted core tool selection for verify and reconfigure defaults.',
    "core_tools=$($env:BOTSTRAP_CORE_TOOLS)"
) | Set-Content -LiteralPath $coreToolsEnvPath -Encoding utf8

$optionalSelectionsPath = Join-Path $configRoot 'optional-selections.env'
@(
    '# Generated by Botstrap phase 3; persisted optional TUI selections for update-tools and reconfigure.',
    "languages=$($env:BOTSTRAP_LANGUAGES)",
    "databases=$($env:BOTSTRAP_DATABASES)",
    "ai_tools=$($env:BOTSTRAP_AI_TOOLS)",
    "optional_apps=$($env:BOTSTRAP_OPTIONAL_APPS)"
) | Set-Content -LiteralPath $optionalSelectionsPath -Encoding utf8

$coreYaml = Join-Path $root 'registry\core.yaml'
Write-BotstrapInfo 'Phase 3 (Windows): selected core tools from registry'
Install-BotstrapToolsFromCsv -Csv $env:BOTSTRAP_CORE_TOOLS -RegistryPath $coreYaml
Refresh-BotstrapPath

if (Test-BotstrapCsvHasItem -Needle 'zellij' -Csv $env:BOTSTRAP_CORE_TOOLS) {
    . (Join-Path $root 'install\modules\zellij.ps1')
    Initialize-BotstrapZellijWindowsConfig
}

$optionalReg = Join-Path $root 'registry\optional.yaml'

Write-BotstrapInfo 'Phase 3 (Windows): optional installs from registry'
if ($env:BOTSTRAP_EDITOR -eq 'neovim') {
    Write-BotstrapInfo 'Skipping optional editor/neovim (installed via core tools).'
}
else {
    [void](Install-BotstrapOptionalItem -GroupId 'editor' -ItemName $env:BOTSTRAP_EDITOR -RegistryPath $optionalReg)
}
Install-BotstrapOptionalCsv -GroupId 'languages' -Csv $env:BOTSTRAP_LANGUAGES -RegistryPath $optionalReg
Install-BotstrapOptionalCsv -GroupId 'databases' -Csv $env:BOTSTRAP_DATABASES -RegistryPath $optionalReg
Install-BotstrapOptionalCsv -GroupId 'ai_tools' -Csv $env:BOTSTRAP_AI_TOOLS -RegistryPath $optionalReg
[void](Install-BotstrapOptionalItem -GroupId 'theme' -ItemName $env:BOTSTRAP_THEME -RegistryPath $optionalReg)
Install-BotstrapOptionalCsv -GroupId 'optional_apps' -Csv $env:BOTSTRAP_OPTIONAL_APPS -RegistryPath $optionalReg

Refresh-BotstrapPath

$gitConfigDir = Join-Path $configBase 'git'

New-Item -ItemType Directory -Force -Path $configRoot | Out-Null
New-Item -ItemType Directory -Force -Path $gitConfigDir | Out-Null
"theme=$($env:BOTSTRAP_THEME)" | Set-Content (Join-Path $configRoot 'theme.env')
"editor=$($env:BOTSTRAP_EDITOR)" | Set-Content (Join-Path $configRoot 'editor.env')

$userGitconfig = Join-Path $env:USERPROFILE '.gitconfig'
$tplGitconfig = Join-Path $root 'configs\git\gitconfig'
if ((Test-Path -LiteralPath $tplGitconfig) -and -not (Test-Path -LiteralPath $userGitconfig)) {
    Copy-Item -LiteralPath $tplGitconfig -Destination $userGitconfig -Force
}

$globalGitignore = Join-Path $env:USERPROFILE '.gitignore_global'
$tplIgnore = Join-Path $root 'configs\git\gitignore_global'
if (Test-Path -LiteralPath $tplIgnore) {
    Copy-Item -LiteralPath $tplIgnore -Destination $globalGitignore -Force
    if (Get-Command git -ErrorAction SilentlyContinue) {
        & git config --global core.excludesfile $globalGitignore
    }
}

if (Get-Command git -ErrorAction SilentlyContinue) {
    & git config --global core.longpaths true
    if ($env:BOTSTRAP_GIT_NAME) {
        & git config --global user.name $env:BOTSTRAP_GIT_NAME
    }
    if ($env:BOTSTRAP_GIT_EMAIL) {
        & git config --global user.email $env:BOTSTRAP_GIT_EMAIL
    }
}

. (Join-Path $root 'lib\git-aliases.ps1')
Install-BotstrapGitAliases

$themeStarship = Join-Path $root "themes\$($env:BOTSTRAP_THEME)\starship.toml"
$promptTpl = Join-Path $root 'configs\shell\prompt.toml'
$starshipOut = Join-Path $configBase 'starship.toml'
if (Test-Path -LiteralPath $themeStarship) {
    Copy-Item -LiteralPath $themeStarship -Destination $starshipOut -Force
}
elseif (Test-Path -LiteralPath $promptTpl) {
    Copy-Item -LiteralPath $promptTpl -Destination $starshipOut -Force
}

function Merge-BotstrapThemeEditorJson {
    param(
        [Parameter(Mandatory)][string]$DestPath,
        [Parameter(Mandatory)][string]$RepoRoot,
        [Parameter(Mandatory)][string]$ThemeId
    )
    $overlay = Join-Path $RepoRoot "themes\$ThemeId\editor.json"
    if (-not (Test-Path -LiteralPath $DestPath) -or -not (Test-Path -LiteralPath $overlay)) {
        return
    }
    try {
        $baseObj = Get-Content -LiteralPath $DestPath -Raw -Encoding utf8 | ConvertFrom-Json
        $overObj = Get-Content -LiteralPath $overlay -Raw -Encoding utf8 | ConvertFrom-Json
    }
    catch {
        return
    }
    $ht = @{}
    foreach ($p in $baseObj.PSObject.Properties) {
        $ht[$p.Name] = $p.Value
    }
    foreach ($p in $overObj.PSObject.Properties) {
        $ht[$p.Name] = $p.Value
    }
    $json = ConvertTo-Json -InputObject $ht -Depth 20
    Set-Content -LiteralPath $DestPath -Value $json -Encoding utf8
}

switch ($env:BOTSTRAP_EDITOR) {
    'cursor' {
        $cursorDir = Join-Path $env:USERPROFILE '.cursor'
        New-Item -ItemType Directory -Force -Path $cursorDir | Out-Null
        $cs = Join-Path $root 'configs\editor\cursor-settings.json'
        if (Test-Path -LiteralPath $cs) {
            $cursorSettings = Join-Path $cursorDir 'settings.json'
            Copy-Item -LiteralPath $cs -Destination $cursorSettings -Force
            Merge-BotstrapThemeEditorJson -DestPath $cursorSettings -RepoRoot $root -ThemeId $env:BOTSTRAP_THEME
        }
    }
    'vscode' {
        $codeUser = Join-Path $env:APPDATA 'Code\User'
        New-Item -ItemType Directory -Force -Path $codeUser | Out-Null
        $vs = Join-Path $root 'configs\editor\vscode.json'
        if (Test-Path -LiteralPath $vs) {
            $vscodeSettings = Join-Path $codeUser 'settings.json'
            Copy-Item -LiteralPath $vs -Destination $vscodeSettings -Force
            Merge-BotstrapThemeEditorJson -DestPath $vscodeSettings -RepoRoot $root -ThemeId $env:BOTSTRAP_THEME
        }
    }
    'neovim' {
        $nvimDir = Join-Path $env:LOCALAPPDATA 'nvim'
        $lazyLua = Join-Path $nvimDir 'lua\config\lazy.lua'
        if (Test-Path -LiteralPath $lazyLua) {
            Write-BotstrapInfo 'LazyVim present; skipping Botstrap minimal init.lua copy.'
        }
        else {
            New-Item -ItemType Directory -Force -Path $nvimDir | Out-Null
            $init = Join-Path $root 'configs\editor\neovim\init.lua'
            if (Test-Path -LiteralPath $init) {
                Copy-Item -LiteralPath $init -Destination (Join-Path $nvimDir 'init.lua') -Force
            }
        }
    }
    default { }
}

$agentDir = Join-Path $configRoot 'agent'
New-Item -ItemType Directory -Force -Path $agentDir | Out-Null
Copy-Item -LiteralPath (Join-Path $root 'configs\agent\AGENTS.md') -Destination (Join-Path $agentDir 'AGENTS.md.sample') -Force -ErrorAction SilentlyContinue
Copy-Item -LiteralPath (Join-Path $root 'configs\agent\cursorrules') -Destination (Join-Path $agentDir 'cursorrules.sample') -Force -ErrorAction SilentlyContinue
Copy-Item -LiteralPath (Join-Path $root 'configs\agent\claude-config.json') -Destination (Join-Path $agentDir 'claude-config.json.sample') -Force -ErrorAction SilentlyContinue

function Add-BotstrapProfileBlock {
    param(
        [Parameter(Mandatory)][string]$ProfilePath,
        [Parameter(Mandatory)][string]$Marker,
        [Parameter(Mandatory)][string]$Block
    )
    $dir = Split-Path -Parent $ProfilePath
    if ($dir -and -not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
    if (-not (Test-Path -LiteralPath $ProfilePath)) {
        New-Item -ItemType File -Force -Path $ProfilePath | Out-Null
    }
    $markerLine = "# $Marker"
    $existing = Get-Content -LiteralPath $ProfilePath -Raw -ErrorAction SilentlyContinue
    if ($existing -and $existing.Contains($markerLine)) {
        $escaped = [regex]::Escape($markerLine)
        $pattern = $escaped + '\r?\n.*?(?=\r?\n# botstrap |\z)'
        $replacement = "$markerLine`n$Block`n"
        $newContent = [regex]::Replace(
            $existing,
            $pattern,
            $replacement,
            [System.Text.RegularExpressions.RegexOptions]::Singleline
        )
        Set-Content -LiteralPath $ProfilePath -Value $newContent -Encoding utf8
        return
    }
    Add-Content -LiteralPath $ProfilePath -Value "`n$markerLine`n$Block`n" -Encoding utf8
}

$starshipBlock = @'
if (Get-Command starship -ErrorAction SilentlyContinue) {
  Invoke-Expression (&starship init powershell)
}
'@

$zoxideBlock = @'
$env:MISE_PWSH_CHPWD_WARNING = "0"
$env:PATH = "$env:LOCALAPPDATA\mise\bin;$env:USERPROFILE\.local\bin;$env:PATH"
if (Get-Command zoxide -ErrorAction SilentlyContinue) {
  if ($PSVersionTable.PSVersion.Major -ge 7) {
    Invoke-Expression (& { (zoxide init powershell | Out-String) })
  } else {
    function global:__zoxide_z {
      param([Parameter(ValueFromRemainingArguments = $true)][string[]]$query)
      if ($query.Count -eq 0) { Set-Location $HOME; return }
      $result = & zoxide query -- @query 2>$null
      if ($LASTEXITCODE -eq 0 -and $result) { Set-Location $result }
    }
    Set-Alias -Name z -Value __zoxide_z -Scope Global -Force -ErrorAction SilentlyContinue
    function global:zi { Write-Warning 'zi requires PowerShell 7+' }
  }
}
'@

$aliasesBlock = @'
if (Get-Command bat -ErrorAction SilentlyContinue) {
  Set-Alias -Name cat -Value bat -Scope Global -Force -ErrorAction SilentlyContinue
}
if (-not (Get-Command BotstrapLl -ErrorAction SilentlyContinue)) {
  function Global:BotstrapLl {
    if (Get-Command eza -ErrorAction SilentlyContinue) {
      & eza -la @args
    }
    else {
      Get-ChildItem @args
    }
  }
}
Set-Alias -Name ll -Value BotstrapLl -Scope Global -Force -ErrorAction SilentlyContinue
'@

$botstrapBin = Join-Path $root 'bin'
$botstrapPathBlock = @"
`$env:BOTSTRAP_ROOT = '$root'
`$env:PATH = "$botstrapBin;`$env:PATH"
function Global:botstrap { & (Join-Path `$env:BOTSTRAP_ROOT 'bin\botstrap.ps1') @args }
"@

$profilePaths = Get-BotstrapWindowsPowerShellProfilePaths
foreach ($profilePath in $profilePaths) {
    Add-BotstrapProfileBlock -ProfilePath $profilePath -Marker 'botstrap PATH' -Block $botstrapPathBlock
    Add-BotstrapProfileBlock -ProfilePath $profilePath -Marker 'botstrap starship' -Block $starshipBlock
    Add-BotstrapProfileBlock -ProfilePath $profilePath -Marker 'botstrap zoxide' -Block $zoxideBlock
    Add-BotstrapProfileBlock -ProfilePath $profilePath -Marker 'botstrap aliases' -Block $aliasesBlock
}

$profilesListed = ($profilePaths -join '; ')
Write-BotstrapInfo "Phase 3 (Windows): config under $configRoot (git, editor=$($env:BOTSTRAP_EDITOR), theme=$($env:BOTSTRAP_THEME)); profiles: $profilesListed"
