#!/usr/bin/env bash
# Phase 3: dotfiles and templates from configs/ based on BOTSTRAP_* env vars.
set -euo pipefail

: "${BOTSTRAP_ROOT:?BOTSTRAP_ROOT must be set}"
# shellcheck source=lib/detect.sh
source "${BOTSTRAP_ROOT}/lib/detect.sh"
# shellcheck source=lib/log.sh
source "${BOTSTRAP_ROOT}/lib/log.sh"
# shellcheck source=lib/pkg.sh
source "${BOTSTRAP_ROOT}/lib/pkg.sh"

botstrap_detect

mkdir -p "${HOME}/.config"
mkdir -p "${HOME}/.config/botstrap"
{
  printf '%s\n' '# Generated by Botstrap phase 3; persisted core tool selection for verify and reconfigure defaults.'
  printf 'core_tools=%s\n' "${BOTSTRAP_CORE_TOOLS:-}"
} >"${HOME}/.config/botstrap/core-tools.env"

{
  printf '%s\n' '# Generated by Botstrap phase 3; persisted optional TUI selections for update-tools and reconfigure.'
  printf 'languages=%s\n' "${BOTSTRAP_LANGUAGES:-}"
  printf 'databases=%s\n' "${BOTSTRAP_DATABASES:-}"
  printf 'ai_tools=%s\n' "${BOTSTRAP_AI_TOOLS:-}"
  printf 'optional_apps=%s\n' "${BOTSTRAP_OPTIONAL_APPS:-}"
} >"${HOME}/.config/botstrap/optional-selections.env"

botstrap_pkg_install_tools_from_csv "${BOTSTRAP_CORE_TOOLS:-}" "${BOTSTRAP_ROOT}/registry/core.yaml"

mkdir -p "${HOME}/.config/git"

if [[ -f "${BOTSTRAP_ROOT}/configs/git/gitconfig" && ! -f "${HOME}/.gitconfig" ]]; then
  cp -f "${BOTSTRAP_ROOT}/configs/git/gitconfig" "${HOME}/.gitconfig"
fi

if [[ "${BOTSTRAP_EDITOR:-none}" == "neovim" ]]; then
  botstrap_log_info "Skipping optional editor/neovim (installed via core tools)."
else
  botstrap_pkg_install_optional_item "editor" "${BOTSTRAP_EDITOR:-none}" "${BOTSTRAP_ROOT}/registry/optional.yaml" || true
fi
botstrap_pkg_install_optional_csv "languages" "${BOTSTRAP_LANGUAGES:-}" "${BOTSTRAP_ROOT}/registry/optional.yaml"
botstrap_pkg_install_optional_csv "databases" "${BOTSTRAP_DATABASES:-}" "${BOTSTRAP_ROOT}/registry/optional.yaml"
botstrap_pkg_install_optional_csv "ai_tools" "${BOTSTRAP_AI_TOOLS:-}" "${BOTSTRAP_ROOT}/registry/optional.yaml"
botstrap_pkg_install_optional_item "theme" "${BOTSTRAP_THEME:-catppuccin}" "${BOTSTRAP_ROOT}/registry/optional.yaml" || true
botstrap_pkg_install_optional_csv "optional_apps" "${BOTSTRAP_OPTIONAL_APPS:-}" "${BOTSTRAP_ROOT}/registry/optional.yaml"

_theme_id="${BOTSTRAP_THEME:-catppuccin}"
_theme_starship="${BOTSTRAP_ROOT}/themes/${_theme_id}/starship.toml"
_prompt_fallback="${BOTSTRAP_ROOT}/configs/shell/prompt.toml"
if [[ -f "${_theme_starship}" ]]; then
  cp -f "${_theme_starship}" "${HOME}/.config/starship.toml"
elif [[ -f "${_prompt_fallback}" ]]; then
  cp -f "${_prompt_fallback}" "${HOME}/.config/starship.toml"
fi

if [[ -f "${BOTSTRAP_ROOT}/configs/git/gitignore_global" ]]; then
  cp -f "${BOTSTRAP_ROOT}/configs/git/gitignore_global" "${HOME}/.gitignore_global"
  git config --global core.excludesfile "${HOME}/.gitignore_global" 2>/dev/null || true
fi

if [[ -n "${BOTSTRAP_GIT_NAME:-}" ]]; then
  git config --global user.name "${BOTSTRAP_GIT_NAME}" 2>/dev/null || true
fi
if [[ -n "${BOTSTRAP_GIT_EMAIL:-}" ]]; then
  git config --global user.email "${BOTSTRAP_GIT_EMAIL}" 2>/dev/null || true
fi

# shellcheck source=lib/git-aliases.sh
source "${BOTSTRAP_ROOT}/lib/git-aliases.sh"
botstrap_git_aliases_apply

_append_block() {
  local file="$1"
  local marker="$2"
  local content="$3"
  [[ -f "${file}" ]] || touch "${file}"
  if grep -q "${marker}" "${file}" 2>/dev/null; then
    return 0
  fi
  {
    printf '\n# %s\n' "${marker}"
    cat "${content}"
    printf '\n'
  } >>"${file}"
}

if [[ -f "${BOTSTRAP_ROOT}/configs/shell/aliases" ]]; then
  [[ -f "${HOME}/.zshrc" ]] || touch "${HOME}/.zshrc"
  _append_block "${HOME}/.zshrc" "botstrap aliases" "${BOTSTRAP_ROOT}/configs/shell/aliases"
  [[ -f "${HOME}/.bashrc" ]] || touch "${HOME}/.bashrc"
  _append_block "${HOME}/.bashrc" "botstrap aliases" "${BOTSTRAP_ROOT}/configs/shell/aliases"
fi

if [[ -f "${BOTSTRAP_ROOT}/configs/shell/functions" ]]; then
  [[ -f "${HOME}/.zshrc" ]] || touch "${HOME}/.zshrc"
  _append_block "${HOME}/.zshrc" "botstrap functions" "${BOTSTRAP_ROOT}/configs/shell/functions"
  [[ -f "${HOME}/.bashrc" ]] || touch "${HOME}/.bashrc"
  _append_block "${HOME}/.bashrc" "botstrap functions" "${BOTSTRAP_ROOT}/configs/shell/functions"
fi

_botstrap_env_sh="${HOME}/.config/botstrap/env.sh"
{
  printf '%s\n' '# Generated by Botstrap phase 3; re-run install or botstrap reconfigure to refresh.'
  printf 'export BOTSTRAP_ROOT=%q\n' "${BOTSTRAP_ROOT}"
  printf '%s\n' 'case ":${PATH}:" in'
  printf '%s\n' '  *:"${BOTSTRAP_ROOT}/bin":*) ;;'
  printf '%s\n' '  *) export PATH="${BOTSTRAP_ROOT}/bin:${PATH}" ;;'
  printf '%s\n' 'esac'
  if [[ "${BOTSTRAP_OS}" == linux ]]; then
    case "${BOTSTRAP_UNAME_M}" in
      x86_64)
        printf '%s\n' 'if [[ -x /opt/nvim-linux-x86_64/bin/nvim ]]; then'
        printf '%s\n' '  case ":${PATH}:" in'
        printf '%s\n' '    *:/opt/nvim-linux-x86_64/bin:*) ;;'
        printf '%s\n' '    *) export PATH="/opt/nvim-linux-x86_64/bin:${PATH}" ;;'
        printf '%s\n' '  esac'
        printf '%s\n' 'fi'
        ;;
      aarch64 | arm64)
        printf '%s\n' 'if [[ -x /opt/nvim-linux-arm64/bin/nvim ]]; then'
        printf '%s\n' '  case ":${PATH}:" in'
        printf '%s\n' '    *:/opt/nvim-linux-arm64/bin:*) ;;'
        printf '%s\n' '    *) export PATH="/opt/nvim-linux-arm64/bin:${PATH}" ;;'
        printf '%s\n' '  esac'
        printf '%s\n' 'fi'
        ;;
    esac
  fi
} >"${_botstrap_env_sh}"

if [[ -f "${BOTSTRAP_ROOT}/configs/shell/env_path_snippet.bash" ]]; then
  [[ -f "${HOME}/.zshrc" ]] || touch "${HOME}/.zshrc"
  _append_block "${HOME}/.zshrc" "botstrap PATH" "${BOTSTRAP_ROOT}/configs/shell/env_path_snippet.bash"
  [[ -f "${HOME}/.bashrc" ]] || touch "${HOME}/.bashrc"
  _append_block "${HOME}/.bashrc" "botstrap PATH" "${BOTSTRAP_ROOT}/configs/shell/env_path_snippet.bash"
fi

_botstrap_merge_theme_editor_json() {
  local dest="$1"
  local overlay="${BOTSTRAP_ROOT}/themes/${_theme_id}/editor.json"
  [[ -f "${dest}" ]] || return 0
  [[ -f "${overlay}" ]] || return 0
  if ! command -v jq &>/dev/null; then
    return 0
  fi
  local tmp
  tmp="$(mktemp)"
  if jq -s '.[0] * .[1]' "${dest}" "${overlay}" >"${tmp}" 2>/dev/null; then
    mv -f "${tmp}" "${dest}"
  else
    rm -f "${tmp}"
  fi
}

case "${BOTSTRAP_EDITOR:-none}" in
  cursor)
    mkdir -p "${HOME}/.cursor"
    if [[ -f "${BOTSTRAP_ROOT}/configs/editor/cursor-settings.json" ]]; then
      cp -f "${BOTSTRAP_ROOT}/configs/editor/cursor-settings.json" "${HOME}/.cursor/settings.json"
      _botstrap_merge_theme_editor_json "${HOME}/.cursor/settings.json"
    fi
    ;;
  vscode)
    mkdir -p "${HOME}/.config/Code/User"
    if [[ -f "${BOTSTRAP_ROOT}/configs/editor/vscode.json" ]]; then
      cp -f "${BOTSTRAP_ROOT}/configs/editor/vscode.json" "${HOME}/.config/Code/User/settings.json"
      _botstrap_merge_theme_editor_json "${HOME}/.config/Code/User/settings.json"
    fi
    ;;
  neovim)
    if [[ -f "${HOME}/.config/nvim/lua/config/lazy.lua" ]]; then
      botstrap_log_info "LazyVim present; skipping Botstrap minimal init.lua copy."
    else
      mkdir -p "${HOME}/.config/nvim"
      if [[ -f "${BOTSTRAP_ROOT}/configs/editor/neovim/init.lua" ]]; then
        cp -f "${BOTSTRAP_ROOT}/configs/editor/neovim/init.lua" "${HOME}/.config/nvim/init.lua"
      fi
    fi
    ;;
  *) ;;
esac

printf '%s\n' "theme=${BOTSTRAP_THEME:-catppuccin}" >"${HOME}/.config/botstrap/theme.env"
printf '%s\n' "editor=${BOTSTRAP_EDITOR:-none}" >"${HOME}/.config/botstrap/editor.env"

mkdir -p "${HOME}/.config/botstrap/agent"
cp -f "${BOTSTRAP_ROOT}/configs/agent/AGENTS.md" "${HOME}/.config/botstrap/agent/AGENTS.md.sample"
cp -f "${BOTSTRAP_ROOT}/configs/agent/cursorrules" "${HOME}/.config/botstrap/agent/cursorrules.sample"
cp -f "${BOTSTRAP_ROOT}/configs/agent/claude-config.json" "${HOME}/.config/botstrap/agent/claude-config.json.sample"

botstrap_log_info "Phase 3 complete (theme=${BOTSTRAP_THEME:-unset})."
